### ISSUE TITLE
Always pulling '10' filings

### ISSUE THREAD

**Issue by strongchong00** [rahulrrixe/SEC-Edgar#10]
No matter what I do, ten filings are always pulled (if ten are available). Changing the input 'count' argument doesn't work. Has the url structure changed or become deprecated? Is that why I'm getting 10 each time? Need a little help.

**Comment by nateraw** [comment]
Count parameter should be one of the following: 10, 20, 40, 80, 100.

Optionally, you can go in and remove it, because it isn't a required parameter.
